# Generated by Django 5.0.3 on 2024-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', models.FileField(upload_to='hotel_images')),
                ('image1', models.FileField(upload_to='hotel_images')),
                ('adress', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=100)),
                ('emails', models.CharField(max_length=100)),
                ('hotel_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('amentities', models.ManyToManyField(to='account.amentities')),
            ],
        ),
    ]
