# Generated by Django 5.0.3 on 2024-04-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.FileField(upload_to='hotel_images')),
                ('image2', models.FileField(upload_to='hotel_images')),
                ('image3', models.FileField(upload_to='hotel_images')),
                ('image4', models.FileField(default=None, upload_to='hotel_images')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Classic', 'classic'), ('Deluxe', 'Deluxe'), ('Saver Single', 'Saver Single'), ('Premium Room With Balcony', 'Premium Room With Balcony'), ('Superior', 'Superior')], max_length=100)),
                ('number_beds', models.PositiveIntegerField(default=0)),
                ('room_capacity', models.PositiveIntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=1000)),
                ('is_available', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.hotel')),
                ('hotel_gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.hotelgallery')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.roomtype')),
            ],
        ),
    ]
