# Generated by Django 5.0.3 on 2024-04-23 07:02

import account.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='check_in_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, validators=[account.models.present_or_future_date]),
        ),
    ]
