# Generated by Django 5.0.3 on 2024-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_hotelbooking_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='num_adults',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='num_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
